# This code is part of Qiskit.
#
# (C) Copyright IBM 2017, 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from collections.abc import Iterable, Iterator
from typing import Any, Self

from qiskit.circuit.annotated_operation import AnnotatedOperation
from qiskit.circuit.operation import Operation
from qiskit.circuit.quantumcircuit import QuantumCircuit

class Instruction(Operation):
    _directive: bool
    _standard_gate: Any
    _name: str
    _num_qubits: int
    _num_clbits: int
    _params: list[Any]
    _label: str | None
    _definition: QuantumCircuit | None

    def __init__(
        self,
        name: str,
        num_qubits: int,
        num_clbits: int,
        params: list[Any],
        label: str | None = ...,
    ) -> None: ...
    @property
    def base_class(self) -> type[Self]: ...
    @property
    def mutable(self) -> bool: ...
    def to_mutable(self) -> Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def soft_compare(self, other: Instruction) -> bool: ...
    def _define(self) -> None: ...
    @property
    def params(self) -> list[Any]: ...
    @params.setter
    def params(self, parameters: Iterable[Any]) -> None: ...
    def validate_parameter(self, parameter: Any) -> Any: ...
    def is_parameterized(self) -> bool: ...
    @property
    def definition(self) -> QuantumCircuit | None: ...
    @definition.setter
    def definition(self, array: QuantumCircuit | None) -> None: ...
    @property
    def decompositions(self) -> list[QuantumCircuit]: ...
    @decompositions.setter
    def decompositions(self, decompositions: list[QuantumCircuit]) -> None: ...
    def add_decomposition(self, decomposition: QuantumCircuit) -> None: ...
    @property
    def label(self) -> str | None: ...
    @label.setter
    def label(self, name: str | None) -> None: ...
    def reverse_ops(self) -> Self: ...
    def inverse(
        self,
        annotated: bool = ...,
    ) -> Instruction | AnnotatedOperation: ...
    def copy(self, name: str | None = ...) -> Self: ...
    def __deepcopy__(self, memo: dict[int, Any] | None = ...) -> Self: ...
    def broadcast_arguments(
        self,
        qargs: list[Any],
        cargs: list[Any],
    ) -> Iterator[tuple[list[Any], list[Any]]]: ...
    def _return_repeat(self, exponent: int) -> Instruction: ...
    def repeat(self, n: int) -> Instruction: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @num_qubits.setter
    def num_qubits(self, num_qubits: int) -> None: ...
    @property
    def num_clbits(self) -> int: ...
    @num_clbits.setter
    def num_clbits(self, num_clbits: int) -> None: ...
    def _compare_parameters(self, other: Instruction) -> bool: ...
