# This code is part of Qiskit.
#
# (C) Copyright IBM 2017, 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root
# directory directory of this source tree or at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from collections.abc import Iterable, Iterator, MappingView
from typing import Any, ClassVar, Generic, TypeVar, overload

_T = TypeVar("_T")

class ParameterView(MappingView, Generic[_T]):
    data: list[_T]

    def __init__(self, iterable: Iterable[_T] | None = None) -> None: ...
    def copy(self) -> ParameterView[_T]: ...
    def isdisjoint(self, x: Iterable[Any]) -> bool: ...
    def remove(self, x: _T) -> None: ...
    def __repr__(self) -> str: ...
    @overload
    def __getitem__(self, index: int) -> _T: ...
    @overload
    def __getitem__(self, index: slice) -> list[_T]: ...
    def __and__(self, x: Iterable[Any]) -> ParameterView[_T]: ...
    def __rand__(self, x: Iterable[Any]) -> ParameterView[_T]: ...
    def __iand__(self, x: Iterable[Any]) -> ParameterView[_T]: ...
    def __len__(self) -> int: ...
    def __or__(self, x: Iterable[Any]) -> set[Any]: ...
    def __sub__(self, x: Iterable[Any]) -> set[Any]: ...
    def __xor__(self, x: Iterable[Any]) -> set[Any]: ...
    def __ne__(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __le__(self, x: Iterable[Any]) -> bool: ...
    def __lt__(self, x: Iterable[Any]) -> bool: ...
    def __ge__(self, x: Iterable[Any]) -> bool: ...
    def __gt__(self, x: Iterable[Any]) -> bool: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __contains__(self, x: object) -> bool: ...
    __hash__: ClassVar[  # pyright: ignore[reportIncompatibleMethodOverride]
        None
    ]
    __ror__ = __or__
