# This code is part of Qiskit.
#
# (C) Copyright IBM 2017, 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from collections.abc import Iterable, Iterator, MutableSequence, Sequence
from typing import Any, overload

import qiskit._accelerate.circuit
from qiskit._accelerate.circuit import Clbit, Qubit
from qiskit.circuit.operation import Operation
from qiskit.circuit.quantumcircuit import QuantumCircuit

CircuitInstruction = (
    qiskit._accelerate.circuit.CircuitInstruction  # noqa: SLF001
)

class QuantumCircuitData(MutableSequence[CircuitInstruction]):
    _circuit: QuantumCircuit

    def __init__(self, circuit: QuantumCircuit) -> None: ...
    @overload
    def __getitem__(self, i: int) -> CircuitInstruction: ...
    @overload
    def __getitem__(self, i: slice) -> list[CircuitInstruction]: ...
    @overload
    def __setitem__(
        self,
        key: int,
        value: CircuitInstruction | tuple[Any, ...],
    ) -> None: ...
    @overload
    def __setitem__(
        self,
        key: slice,
        value: Iterable[CircuitInstruction | tuple[Any, ...]],
    ) -> None: ...
    def _resolve_legacy_value(
        self,
        operation: Operation,
        qargs: Sequence[Qubit],
        cargs: Sequence[Clbit],
    ) -> CircuitInstruction: ...
    def insert(
        self,
        index: int,
        value: CircuitInstruction | tuple[Any, ...],
    ) -> None: ...
    def __iter__(self) -> Iterator[CircuitInstruction]: ...
    def __delitem__(self, i: int | slice) -> None: ...
    def __len__(self) -> int: ...
    def __cast(self, other: Any) -> list[Any]: ...
    def __repr__(self) -> str: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __add__(self, other: Any) -> list[CircuitInstruction]: ...
    def __radd__(self, other: Any) -> list[CircuitInstruction]: ...
    def __mul__(self, n: int) -> list[CircuitInstruction]: ...
    def __rmul__(self, n: int) -> list[CircuitInstruction]: ...
    def sort(self, *args: Any, **kwargs: Any) -> None: ...
    def copy(self) -> list[CircuitInstruction]: ...
