# ruff: noqa: A002

# This code is part of Qiskit.
#
# (C) Copyright IBM 2017, 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from enum import Enum
from typing import Any

class Expr: ...

class Var(Expr):
    name: str | None
    var: Any
    def __init__(
        self,
        var: Any,
        type: type,
        *,
        name: str | None = ...,
    ) -> None: ...
    @classmethod
    def new(cls, name: str, ty: type) -> Var: ...

class Stretch:
    name: str
    var: Any
    def __init__(self, var: Any, name: str) -> None: ...
    @classmethod
    def new(cls, name: str) -> Stretch: ...

class Value:
    value: Any
    def __init__(self, value: Any, type: type) -> None: ...

class Cast:
    def __init__(
        self,
        operand: Expr,
        type: type,
        implicit: bool = False,
    ) -> None: ...

class Unary:
    class Op(Enum):
        BIT_NOT = ...
        LOGIC_NOT = ...
        NEGATE = ...

    def __init__(self, op: Op, operand: Expr, type: type) -> None: ...

class Binary:
    class Op(Enum):
        BIT_AND = ...
        BIT_OR = ...
        BIT_XOR = ...
        LOGIC_AND = ...
        LOGIC_OR = ...
        EQUAL = ...
        NOT_EQUAL = ...
        LESS = ...
        LESS_EQUAL = ...
        GREATER = ...
        GREATER_EQUAL = ...
        SHIFT_LEFT = ...
        SHIFT_RIGHT = ...
        ADD = ...
        SUB = ...
        MUL = ...
        DIV = ...

    def __init__(
        self,
        op: Op,
        left: Expr,
        right: Expr,
        type: type,
    ) -> None: ...

class Index:
    def __init__(self, target: Expr, index: Expr, type: type) -> None: ...
